[project]
name = "bsoyka-infra"
version = "0.1.0"
description = "Infrastructure-as-code for my personal projects"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dns = ["octodns>=1.12.0", "octodns-cloudflare>=1.0.0"]
