name: Deploy DNS changes

on:
  push:
    branches:
      - main
    paths:
      - 'dns/**'
  workflow_dispatch:

jobs:
  octodns-sync:
    environment: production
    name: Deploy DNS changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'
      - name: "Install project dependencies"
        run: pip install -r requirements.txt
      - uses: solvaholic/octodns-sync@v3.1.1
        id: generate-plan
        with:
          config_path: dns/config.yaml
          force: "Yes"
          doit: "--doit"
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_EDIT_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}
