name: Deploy DNS changes

on:
  push:
    branches:
      - main
    paths:
      - 'dns/**'

jobs:
  octodns-sync:
    environment: production
    name: Deploy DNS changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.0"
      - name: "Install DNS tooling dependencies"
        run: uv sync --group dns
      - uses: solvaholic/octodns-sync@v3.1.1
        id: generate-plan
        with:
          config_path: dns/config.yaml
          force: "Yes"
          doit: "--doit"
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_EDIT_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
